Website = "https://github.com/craig-warner/mandelbrot-background"

[Details]
  Icon = "assets/mandelbrot-background.png"
  Name = "Mandelbrot Background"
  ID = "com.warnerbits.mandelbrotbackground"
  Version = "1.0.0"
  Build = 5
